config/routes.rb
Sandbox::Application.routes.draw do
  get "home/index"

  get "ws_test/show"

  get "dashboard/index"

  get "dirmon/index"

  root :to => 'home#index'

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  validates_presence_of :text
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def load_yaml(filename)
    yaml = ""
    if filename && File.exists?( filename)
      yaml = YAML.load_file filename
    end
    yaml
  end
  
  #--------------------------------------------------------------------------
  # Method: pref_val
  #
  # returns the value of a preference key from the yaml file
  #         , sec - secondary key
  #--------------------------------------------------------------------------
  def pref_val(key, sec=null)
    current = cookies["current_pref_file"]
    current = Sandbox::Application.config.default_preference_file unless current
    preference = load_yaml current
    if sec
      val = preference[key.to_s][sec.to_s]
    else
      val = preference[ket.to_s]
    end
    val
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  has_widgets do |root|
    root << panel = widget("twitter/panel", :twitter)
  end
   
  def index
  end
end

app/controllers/dirmon_controller.rb
class DirmonController < ApplicationController
  
  has_widgets do |root|
    #logfile = pref_val :logfile
    #srv_uri = pref_val :srv_uri
    #user = pref_val: :user
    logfile = Rails.root.join 'log', 'development.log'
    srv_uri = 'druby://localhost:6789'
    user = 'kal'
    groups = %w[. .. ~]
    groups.map! {|dir| File.expand_path dir}
    #binding.pry
    root << widget( :status, :uri => srv_uri, :user => user)
    groups.each do |group|
      name = File.basename group
      dirs = Dir.entries(group).reject! {|f| f[0] == "."}
      dirs = dirs.select {|d| File.directory?(File.join group, d)}
      dirs.map! {|f| File.join(group, f)}
      root << widget(:groupbar, name, :dirs => dirs)
    end
    root << widget(:logview, :logfile => logfile)    
  end
  
  def index
    @severity = ""
    @alert_msg = ""
    @groups = %w[. .. ~]
    @groups.map! {|dir| File.basename File.expand_path(dir)}
    
    respond_to do |format|
      format.html
      format.json {render json: @groups}
    end
  end
  
  def alert
    # .alert-box.success
    #   Dude! it works
    # .alert-box.warning
    #   Cautione is advised
    # .alert-box.error
    #   Danger Will Robinson!!!
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @default_config = {}
  end
end

app/controllers/ws_test_controller.rb
class WsTestController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/dirmon_helper.rb
module DirmonHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ws_test_helper.rb
module WsTestHelper
end

app/views/dashboard/index.html.haml
%h1 My Dashboard

#dashboard
  .column
    = render_widget :twitter

app/views/dirmon/index.html.haml
- content_for :page_title do
  DirMonitor

.container
  .row
    .twelve.columns
      .alert_panel.hide
        .alert-box{:class => @severity}
          = @alert_msg
      %h1 Dirmon
      
      = render_widget :status, :show
      - @groups.each do |group|
        = render_widget group, :show
      = render_widget :logview, :show

app/views/home/index.html.haml
- content_for :page_title do
  Sandbox Home
  
.container
  .row
    .eight.columns.centered
      %h2 Hello Rails
      %a.group_bar{:href => "#", "data-reveal-id" => "default_config"}
        Show Default Config
      %p
        = form_tag({:action => :upload}, :multipart => true) do
          = file_field_tag 'pref_file', :size => 50
          = submit_tag "Upload"
      .panel.hide
        = link_to "The Blog", dashboard_index_path
        
  #default_config.reveal-modal
    -#:coderay
    -#  #!yaml
    -#    #{@default_config.to_s}
    %h3 Default configuration
    /= "#{@config_file}"
    .container
      = form_tag do
        - @default_config.keys.each do |type|
          %h4
            = "#{type}:"
          - a = @default_config[type]
          %ul
            - a.keys.each do |entry|
              %li
                = label_tag entry
                = text_field_tag "#{entry}", "#{a[entry]}", :size => 40
        = submit_tag "Save"
        = submit_tag "Cancel"
    %a.close-reveal-modal x

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  / <![endif]
  %head
    %meta{:charset => "utf-8"}/
    / Set the viewport width to device width for mobile
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Untitled"
    / Included CSS Files
    = stylesheet_link_tag    "application"
    / Included JS Files
    = javascript_include_tag "application"
    = csrf_meta_tags
    /[if lt IE 9]
      = javascript_include_tag "html5shiv"
  %body
    .container
      .row
        %dl.nice.tabs
          %dd
            %a{:href => "/"} Home &nbsp;
          %dd
            %a{:href => "/dirmon/index"} Dirmon &nbsp;
          %dd
            %a{:href => "/dashboard/index"} Dashboard &nbsp;
            
      .row
        = yield

app/views/ws_test/show.html.haml
:javascript
  $(document).ready(function(){
      function debug(str){ $("#debug").append("<p>"+str+"</p>"); };

      ws = new WebSocket("ws://localhost:8080");
      ws.onmessage = function(evt) { $("#msg").append("<p>"+evt.data+"</p>"); };
      ws.onclose = function() { debug("socket closed"); };
      ws.onopen = function() {
        debug("connected...");
        ws.send("hello server");
      };
    });

%h1 WsTest#show
#debug
#msg